CONFIG_ZMK_KEYBOARD_NAME="Tux"

CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# Power saving
CONFIG_ZMK_SLEEP=y
# 30 min → deep sleep
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Mouse emulation
CONFIG_ZMK_POINTING=y

# Display - 128×32 OLED, mounted vertically (portrait via custom rotation flush)
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_LV_USE_THEME_MONO=y
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_FONT_PLACEHOLDER=y
CONFIG_LV_Z_MEM_POOL_SIZE=8192
CONFIG_SSD1306_DEFAULT_CONTRAST=0
CONFIG_ZMK_DISPLAY_INVERT=y
